# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1612b65ff43067f13fe6e444ebe5dd9c5fbfd433c28c6a3749633d43bbaff5b5983eef34a7dbccc976ece48677265e61ddec556877e1888aa1386b4597c8c348

test:
  secret_key_base: eb090c4bda22c4750344068672093fb19713eeb9e8c2db6c743435a3b7f882cfa8e4ff6c7893bd27ecae9eea63f8a102c74bb19aafa6e73cf36bf557a5560dd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
